# Generated by Django 6.0.5 on 2026-05-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_brand_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Aurum Collection', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
