# Generated by Django 6.0.5 on 2026-06-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_pendingsignup_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingSignup',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
