# Generated by Django 6.0.5 on 2026-06-22 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_socialaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list)),
                ('model_version', models.CharField(max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='shop.product')),
            ],
            options={
                'indexes': [models.Index(fields=['model_version'], name='shop_produc_model_v_4f3d32_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('add_to_cart', 'Add to cart'), ('remove_from_cart', 'Remove from cart'), ('checkout', 'Checkout'), ('purchase', 'Purchase')], max_length=30)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='shop.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='shop_produc_user_id_103406_idx'), models.Index(fields=['session_key', 'created_at'], name='shop_produc_session_2c1cd3_idx'), models.Index(fields=['product', 'event_type'], name='shop_produc_product_fd8ae9_idx')],
            },
        ),
    ]
