# Generated by Django 6.0.5 on 2026-06-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_choice',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
