# Generated by Django 6.0.5 on 2026-07-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_tag_product_description_product_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='shop.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='created', max_length=30),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_refund_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], max_length=30)),
                ('speed_requested', models.CharField(blank=True, default='', max_length=30)),
                ('speed_processed', models.CharField(blank=True, default='', max_length=30)),
                ('receipt', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='shop.payment')),
            ],
        ),
    ]
