# Generated by Django 6.0.5 on 2026-07-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_chatconversation_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_ai_message',
            field=models.BooleanField(default=False),
        ),
    ]
