# Generated by Django 6.0.5 on 2026-07-08 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_refund_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('qc_passed', 'QC Passed'), ('refunded', 'Refunded')], default='requested', max_length=30)),
                ('reason', models.CharField(choices=[('defective', 'Defective'), ('wrong_item', 'Wrong Item'), ('changed_mind', 'Changed Mind'), ('quality_issue', 'Quality Issue')], max_length=30)),
                ('reason_detail', models.TextField(blank=True, default='')),
                ('refund_mode', models.CharField(choices=[('original_payment', 'Original Payment'), ('wallet', 'Wallet')], default='original_payment', max_length=30)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='shop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField(default=1)),
                ('item_condition_notes', models.TextField(blank=True, default='')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request_items', to='shop.orderitem')),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.refundrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RefundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='refund_requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.refundrequest')),
            ],
        ),
    ]
