# Generated by Django 6.0.5 on 2026-07-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_refundrequest_refunditem_refundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('defective', 'Defective'), ('wrong_item', 'Wrong Item'), ('changed_mind', 'Changed Mind'), ('quality_issue', 'Quality Issue')], max_length=30),
        ),
    ]
