# Generated by Django 6.0.5 on 2026-07-09 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_requested_to_pending_review(apps, schema_editor):
    RefundRequest = apps.get_model('shop', 'RefundRequest')
    RefundRequest.objects.filter(status='requested').update(status='pending_review')


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_refundrequest_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_refund_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='staff_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.CharField(choices=[('defective', 'Defective'), ('wrong_item', 'Wrong Item'), ('changed_mind', 'Changed Mind'), ('quality_issue', 'Quality Issue')], max_length=30),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('refunded', 'Refunded')], default='pending_review', max_length=30),
        ),
        migrations.RunPython(move_requested_to_pending_review, migrations.RunPython.noop),
    ]
