# Generated by Django 6.0.5 on 2026-07-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_subcategory_product_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
