# Generated by Django 6.0.5 on 2026-07-14 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=40, null=True)),
                ('purity', models.CharField(blank=True, max_length=20, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ('size', 'purity', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_purity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_size',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productstockvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_variants', to='shop.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='stock_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productstockvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productstockvariant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'stock_variant'), name='unique_cart_product_stock_variant'),
        ),
        migrations.AlterUniqueTogether(
            name='productstockvariant',
            unique_together={('product', 'size', 'purity')},
        ),
    ]
