# Generated by Django 6.0.5 on 2026-07-15 06:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_productstockvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gemstone_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='making_charge_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5),
        ),
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum')], db_index=True, max_length=20)),
                ('purity', models.CharField(blank=True, max_length=20, null=True)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(default='metalpriceapi', max_length=30)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-fetched_at', '-id'),
                'indexes': [models.Index(fields=['metal', 'purity', '-fetched_at'], name='metal_rate_latest_idx')],
            },
        ),
    ]
